services:
  - type: web
    name: enterprise-order-system-v8
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: enterprise-order-system-v8
          property: port
    domains:
      - your-custom-domain.com  # Optional: ใส่ custom domain ถ้ามี
